on:
  push:
    branches:
      - main
name: 🚀 Deploy on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔧 Use Node.js 22
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
          npm prune --production

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/
          server-dir: /api/
          exclude: |
            **/.git*
            **/node_modules/**
            **/package-lock.json**
